In [140]:
import numpy as np


In [141]:
input_value= np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [142]:
output_value= np.array([[0],[1],[1],[0]])
output_value=output_value.reshape(4,1)
# output_value.shape
output_value

array([[0],
       [1],
       [1],
       [0]])

In [143]:
weight = np.array([[0.1],[0.2]])
weight

array([[0.1],
       [0.2]])

In [144]:
# np.random.seed(1)
# weight = np.random.rand(2, 1)
# bias = np.random.rand(1)

In [145]:
bias=0.3

In [146]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [147]:
def der_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

In [148]:
def relu(x):
    return np.maximum(0, x)

In [149]:
def der_relu(x):
    return np.where(x > 0, 1, 0)

In [150]:
def tanh(x):
    return np.tanh(x)

In [151]:
def der_tanh(x):
    return 1 - np.tanh(x)**2

In [152]:
activation = sigmoid
der_activation = der_sigmoid

In [157]:
for epochs in range(10000):
    input_layer=input_value
    weighted_sum=np.dot(input_layer,weight)+bias
    output=activation(weighted_sum)
    error=output_value-output
    total_error=np.square(np.subtract(output_value,output)).mean()
    #print(total_error)
    slope=der_activation(output)
    delta=error*slope
    weight=weight - 0.01 * np.dot(input_layer.T,delta)
    for i in delta:
        bias=bias - 0.01 * i
print(weight)
print(bias)

[[215.36739508]
 [ -1.80114824]]
[430.13395007]


In [158]:
pred=np.array([1,0])
result=np.dot(pred,weight)+bias
res = activation(result)
print(res)

[1.]
